// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bag.proto

// Protobuf Java Version: 3.25.3
package com.github.jameshnsears.chance.data.domain.proto;

/**
 * Protobuf type {@code com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer}
 */
public final class BagProtocolBuffer extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer)
        BagProtocolBufferOrBuilder {
    public static final int DICE_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer)
    private static final com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<BagProtocolBuffer>
            PARSER = new com.google.protobuf.AbstractParser<BagProtocolBuffer>() {
        @java.lang.Override
        public BagProtocolBuffer parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        DEFAULT_INSTANCE = new com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer();
    }

    @SuppressWarnings("serial")
    private java.util.List<com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer> dice_;
    private byte memoizedIsInitialized = -1;
    // Use BagProtocolBuffer.newBuilder() to construct.
    private BagProtocolBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private BagProtocolBuffer() {
        dice_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.github.jameshnsears.chance.data.domain.proto.Bag.internal_static_com_github_jameshnsears_chance_data_domain_proto_BagProtocolBuffer_descriptor;
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<BagProtocolBuffer> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new BagProtocolBuffer();
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.github.jameshnsears.chance.data.domain.proto.Bag.internal_static_com_github_jameshnsears_chance_data_domain_proto_BagProtocolBuffer_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.class, com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.Builder.class);
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer> getDiceList() {
        return dice_;
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder>
    getDiceOrBuilderList() {
        return dice_;
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
     */
    @java.lang.Override
    public int getDiceCount() {
        return dice_.size();
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
     */
    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer getDice(int index) {
        return dice_.get(index);
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
     */
    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder getDiceOrBuilder(
            int index) {
        return dice_.get(index);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < dice_.size(); i++) {
            output.writeMessage(1, dice_.get(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < dice_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, dice_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer)) {
            return super.equals(obj);
        }
        com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer other = (com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer) obj;

        if (!getDiceList()
                .equals(other.getDiceList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getDiceCount() > 0) {
            hash = (37 * hash) + DICE_FIELD_NUMBER;
            hash = (53 * hash) + getDiceList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BagProtocolBuffer> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer)
            com.github.jameshnsears.chance.data.domain.proto.BagProtocolBufferOrBuilder {
        private int bitField0_;
        private java.util.List<com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer> dice_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder> diceBuilder_;

        // Construct using com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.jameshnsears.chance.data.domain.proto.Bag.internal_static_com_github_jameshnsears_chance_data_domain_proto_BagProtocolBuffer_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.jameshnsears.chance.data.domain.proto.Bag.internal_static_com_github_jameshnsears_chance_data_domain_proto_BagProtocolBuffer_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.class, com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            if (diceBuilder_ == null) {
                dice_ = java.util.Collections.emptyList();
            } else {
                dice_ = null;
                diceBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.github.jameshnsears.chance.data.domain.proto.Bag.internal_static_com_github_jameshnsears_chance_data_domain_proto_BagProtocolBuffer_descriptor;
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer getDefaultInstanceForType() {
            return com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.getDefaultInstance();
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer build() {
            com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer buildPartial() {
            com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer result = new com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer result) {
            if (diceBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    dice_ = java.util.Collections.unmodifiableList(dice_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.dice_ = dice_;
            } else {
                result.dice_ = diceBuilder_.build();
            }
        }

        private void buildPartial0(com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer result) {
            int from_bitField0_ = bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer) {
                return mergeFrom((com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer other) {
            if (other == com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer.getDefaultInstance())
                return this;
            if (diceBuilder_ == null) {
                if (!other.dice_.isEmpty()) {
                    if (dice_.isEmpty()) {
                        dice_ = other.dice_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureDiceIsMutable();
                        dice_.addAll(other.dice_);
                    }
                    onChanged();
                }
            } else {
                if (!other.dice_.isEmpty()) {
                    if (diceBuilder_.isEmpty()) {
                        diceBuilder_.dispose();
                        diceBuilder_ = null;
                        dice_ = other.dice_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        diceBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getDiceFieldBuilder() : null;
                    } else {
                        diceBuilder_.addAllMessages(other.dice_);
                    }
                }
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer m =
                                    input.readMessage(
                                            com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.parser(),
                                            extensionRegistry);
                            if (diceBuilder_ == null) {
                                ensureDiceIsMutable();
                                dice_.add(m);
                            } else {
                                diceBuilder_.addMessage(m);
                            }
                            break;
                        } // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private void ensureDiceIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                dice_ = new java.util.ArrayList<com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer>(dice_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public java.util.List<com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer> getDiceList() {
            if (diceBuilder_ == null) {
                return java.util.Collections.unmodifiableList(dice_);
            } else {
                return diceBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public int getDiceCount() {
            if (diceBuilder_ == null) {
                return dice_.size();
            } else {
                return diceBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer getDice(int index) {
            if (diceBuilder_ == null) {
                return dice_.get(index);
            } else {
                return diceBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder setDice(
                int index, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer value) {
            if (diceBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureDiceIsMutable();
                dice_.set(index, value);
                onChanged();
            } else {
                diceBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder setDice(
                int index, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder builderForValue) {
            if (diceBuilder_ == null) {
                ensureDiceIsMutable();
                dice_.set(index, builderForValue.build());
                onChanged();
            } else {
                diceBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder addDice(com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer value) {
            if (diceBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureDiceIsMutable();
                dice_.add(value);
                onChanged();
            } else {
                diceBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder addDice(
                int index, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer value) {
            if (diceBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureDiceIsMutable();
                dice_.add(index, value);
                onChanged();
            } else {
                diceBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder addDice(
                com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder builderForValue) {
            if (diceBuilder_ == null) {
                ensureDiceIsMutable();
                dice_.add(builderForValue.build());
                onChanged();
            } else {
                diceBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder addDice(
                int index, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder builderForValue) {
            if (diceBuilder_ == null) {
                ensureDiceIsMutable();
                dice_.add(index, builderForValue.build());
                onChanged();
            } else {
                diceBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder addAllDice(
                java.lang.Iterable<? extends com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer> values) {
            if (diceBuilder_ == null) {
                ensureDiceIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, dice_);
                onChanged();
            } else {
                diceBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder clearDice() {
            if (diceBuilder_ == null) {
                dice_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                diceBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public Builder removeDice(int index) {
            if (diceBuilder_ == null) {
                ensureDiceIsMutable();
                dice_.remove(index);
                onChanged();
            } else {
                diceBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder getDiceBuilder(
                int index) {
            return getDiceFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder getDiceOrBuilder(
                int index) {
            if (diceBuilder_ == null) {
                return dice_.get(index);
            } else {
                return diceBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public java.util.List<? extends com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder>
        getDiceOrBuilderList() {
            if (diceBuilder_ != null) {
                return diceBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(dice_);
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder addDiceBuilder() {
            return getDiceFieldBuilder().addBuilder(
                    com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.getDefaultInstance());
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder addDiceBuilder(
                int index) {
            return getDiceFieldBuilder().addBuilder(
                    index, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.getDefaultInstance());
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer dice = 1;</code>
         */
        public java.util.List<com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder>
        getDiceBuilderList() {
            return getDiceFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder>
        getDiceFieldBuilder() {
            if (diceBuilder_ == null) {
                diceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder>(
                        dice_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                dice_ = null;
            }
            return diceBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.github.jameshnsears.chance.data.domain.proto.BagProtocolBuffer)
    }

}

