// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

// Protobuf Java Version: 3.25.1
package com.github.jameshnsears.chance.data.domain.proto;

/**
 * Protobuf type {@code com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer}
 */
public final class DiceProtocolBuffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer)
    DiceProtocolBufferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DiceProtocolBuffer.newBuilder() to construct.
  private DiceProtocolBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DiceProtocolBuffer() {
    side_ = java.util.Collections.emptyList();
    title_ = "";
    colour_ = "";
    explodeWhen_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DiceProtocolBuffer();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.jameshnsears.chance.data.domain.proto.Dice.internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceProtocolBuffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.jameshnsears.chance.data.domain.proto.Dice.internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceProtocolBuffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.class, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder.class);
  }

  public static final int EPOCH_FIELD_NUMBER = 1;
  private long epoch_ = 0L;
  /**
   * <code>int64 epoch = 1;</code>
   * @return The epoch.
   */
  @java.lang.Override
  public long getEpoch() {
    return epoch_;
  }

  public static final int SIDE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer> side_;
  /**
   * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer> getSideList() {
    return side_;
  }
  /**
   * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder> 
      getSideOrBuilderList() {
    return side_;
  }
  /**
   * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
   */
  @java.lang.Override
  public int getSideCount() {
    return side_.size();
  }
  /**
   * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
   */
  @java.lang.Override
  public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer getSide(int index) {
    return side_.get(index);
  }
  /**
   * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
   */
  @java.lang.Override
  public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder getSideOrBuilder(
      int index) {
    return side_.get(index);
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLESTRINGSID_FIELD_NUMBER = 4;
  private int titleStringsId_ = 0;
  /**
   * <code>int32 titleStringsId = 4;</code>
   * @return The titleStringsId.
   */
  @java.lang.Override
  public int getTitleStringsId() {
    return titleStringsId_;
  }

  public static final int COLOUR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object colour_ = "";
  /**
   * <code>string colour = 5;</code>
   * @return The colour.
   */
  @java.lang.Override
  public java.lang.String getColour() {
    java.lang.Object ref = colour_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      colour_ = s;
      return s;
    }
  }
  /**
   * <code>string colour = 5;</code>
   * @return The bytes for colour.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColourBytes() {
    java.lang.Object ref = colour_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      colour_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELECTED_FIELD_NUMBER = 6;
  private boolean selected_ = false;
  /**
   * <code>bool selected = 6;</code>
   * @return The selected.
   */
  @java.lang.Override
  public boolean getSelected() {
    return selected_;
  }

  public static final int MULTIPLIER_FIELD_NUMBER = 7;
  private boolean multiplier_ = false;
  /**
   * <code>bool multiplier = 7;</code>
   * @return The multiplier.
   */
  @java.lang.Override
  public boolean getMultiplier() {
    return multiplier_;
  }

  public static final int MULTIPLIERVALUE_FIELD_NUMBER = 8;
  private int multiplierValue_ = 0;
  /**
   * <code>int32 multiplierValue = 8;</code>
   * @return The multiplierValue.
   */
  @java.lang.Override
  public int getMultiplierValue() {
    return multiplierValue_;
  }

  public static final int EXPLODE_FIELD_NUMBER = 9;
  private boolean explode_ = false;
  /**
   * <code>bool explode = 9;</code>
   * @return The explode.
   */
  @java.lang.Override
  public boolean getExplode() {
    return explode_;
  }

  public static final int EXPLODEWHEN_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object explodeWhen_ = "";
  /**
   * <code>string explodeWhen = 10;</code>
   * @return The explodeWhen.
   */
  @java.lang.Override
  public java.lang.String getExplodeWhen() {
    java.lang.Object ref = explodeWhen_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      explodeWhen_ = s;
      return s;
    }
  }
  /**
   * <code>string explodeWhen = 10;</code>
   * @return The bytes for explodeWhen.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExplodeWhenBytes() {
    java.lang.Object ref = explodeWhen_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      explodeWhen_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPLODEVALUE_FIELD_NUMBER = 11;
  private int explodeValue_ = 0;
  /**
   * <code>int32 explodeValue = 11;</code>
   * @return The explodeValue.
   */
  @java.lang.Override
  public int getExplodeValue() {
    return explodeValue_;
  }

  public static final int MODIFYSCORE_FIELD_NUMBER = 12;
  private boolean modifyScore_ = false;
  /**
   * <code>bool modifyScore = 12;</code>
   * @return The modifyScore.
   */
  @java.lang.Override
  public boolean getModifyScore() {
    return modifyScore_;
  }

  public static final int MODIFYSCOREVALUE_FIELD_NUMBER = 13;
  private int modifyScoreValue_ = 0;
  /**
   * <code>int32 modifyScoreValue = 13;</code>
   * @return The modifyScoreValue.
   */
  @java.lang.Override
  public int getModifyScoreValue() {
    return modifyScoreValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (epoch_ != 0L) {
      output.writeInt64(1, epoch_);
    }
    for (int i = 0; i < side_.size(); i++) {
      output.writeMessage(2, side_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (titleStringsId_ != 0) {
      output.writeInt32(4, titleStringsId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colour_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, colour_);
    }
    if (selected_ != false) {
      output.writeBool(6, selected_);
    }
    if (multiplier_ != false) {
      output.writeBool(7, multiplier_);
    }
    if (multiplierValue_ != 0) {
      output.writeInt32(8, multiplierValue_);
    }
    if (explode_ != false) {
      output.writeBool(9, explode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(explodeWhen_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, explodeWhen_);
    }
    if (explodeValue_ != 0) {
      output.writeInt32(11, explodeValue_);
    }
    if (modifyScore_ != false) {
      output.writeBool(12, modifyScore_);
    }
    if (modifyScoreValue_ != 0) {
      output.writeInt32(13, modifyScoreValue_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (epoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, epoch_);
    }
    for (int i = 0; i < side_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, side_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (titleStringsId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, titleStringsId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colour_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, colour_);
    }
    if (selected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, selected_);
    }
    if (multiplier_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, multiplier_);
    }
    if (multiplierValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, multiplierValue_);
    }
    if (explode_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, explode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(explodeWhen_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, explodeWhen_);
    }
    if (explodeValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, explodeValue_);
    }
    if (modifyScore_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, modifyScore_);
    }
    if (modifyScoreValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, modifyScoreValue_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer)) {
      return super.equals(obj);
    }
    com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer other = (com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer) obj;

    if (getEpoch()
        != other.getEpoch()) return false;
    if (!getSideList()
        .equals(other.getSideList())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (getTitleStringsId()
        != other.getTitleStringsId()) return false;
    if (!getColour()
        .equals(other.getColour())) return false;
    if (getSelected()
        != other.getSelected()) return false;
    if (getMultiplier()
        != other.getMultiplier()) return false;
    if (getMultiplierValue()
        != other.getMultiplierValue()) return false;
    if (getExplode()
        != other.getExplode()) return false;
    if (!getExplodeWhen()
        .equals(other.getExplodeWhen())) return false;
    if (getExplodeValue()
        != other.getExplodeValue()) return false;
    if (getModifyScore()
        != other.getModifyScore()) return false;
    if (getModifyScoreValue()
        != other.getModifyScoreValue()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEpoch());
    if (getSideCount() > 0) {
      hash = (37 * hash) + SIDE_FIELD_NUMBER;
      hash = (53 * hash) + getSideList().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + TITLESTRINGSID_FIELD_NUMBER;
    hash = (53 * hash) + getTitleStringsId();
    hash = (37 * hash) + COLOUR_FIELD_NUMBER;
    hash = (53 * hash) + getColour().hashCode();
    hash = (37 * hash) + SELECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSelected());
    hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMultiplier());
    hash = (37 * hash) + MULTIPLIERVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getMultiplierValue();
    hash = (37 * hash) + EXPLODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExplode());
    hash = (37 * hash) + EXPLODEWHEN_FIELD_NUMBER;
    hash = (53 * hash) + getExplodeWhen().hashCode();
    hash = (37 * hash) + EXPLODEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getExplodeValue();
    hash = (37 * hash) + MODIFYSCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getModifyScore());
    hash = (37 * hash) + MODIFYSCOREVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getModifyScoreValue();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer)
      com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBufferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.jameshnsears.chance.data.domain.proto.Dice.internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceProtocolBuffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.jameshnsears.chance.data.domain.proto.Dice.internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceProtocolBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.class, com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.Builder.class);
    }

    // Construct using com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      epoch_ = 0L;
      if (sideBuilder_ == null) {
        side_ = java.util.Collections.emptyList();
      } else {
        side_ = null;
        sideBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      title_ = "";
      titleStringsId_ = 0;
      colour_ = "";
      selected_ = false;
      multiplier_ = false;
      multiplierValue_ = 0;
      explode_ = false;
      explodeWhen_ = "";
      explodeValue_ = 0;
      modifyScore_ = false;
      modifyScoreValue_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.jameshnsears.chance.data.domain.proto.Dice.internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceProtocolBuffer_descriptor;
    }

    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer getDefaultInstanceForType() {
      return com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer build() {
      com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer buildPartial() {
      com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer result = new com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer result) {
      if (sideBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          side_ = java.util.Collections.unmodifiableList(side_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.side_ = side_;
      } else {
        result.side_ = sideBuilder_.build();
      }
    }

    private void buildPartial0(com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.epoch_ = epoch_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.titleStringsId_ = titleStringsId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.colour_ = colour_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.selected_ = selected_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.multiplier_ = multiplier_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.multiplierValue_ = multiplierValue_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.explode_ = explode_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.explodeWhen_ = explodeWhen_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.explodeValue_ = explodeValue_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.modifyScore_ = modifyScore_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.modifyScoreValue_ = modifyScoreValue_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer) {
        return mergeFrom((com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer other) {
      if (other == com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer.getDefaultInstance()) return this;
      if (other.getEpoch() != 0L) {
        setEpoch(other.getEpoch());
      }
      if (sideBuilder_ == null) {
        if (!other.side_.isEmpty()) {
          if (side_.isEmpty()) {
            side_ = other.side_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSideIsMutable();
            side_.addAll(other.side_);
          }
          onChanged();
        }
      } else {
        if (!other.side_.isEmpty()) {
          if (sideBuilder_.isEmpty()) {
            sideBuilder_.dispose();
            sideBuilder_ = null;
            side_ = other.side_;
            bitField0_ = (bitField0_ & ~0x00000002);
            sideBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSideFieldBuilder() : null;
          } else {
            sideBuilder_.addAllMessages(other.side_);
          }
        }
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getTitleStringsId() != 0) {
        setTitleStringsId(other.getTitleStringsId());
      }
      if (!other.getColour().isEmpty()) {
        colour_ = other.colour_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getSelected() != false) {
        setSelected(other.getSelected());
      }
      if (other.getMultiplier() != false) {
        setMultiplier(other.getMultiplier());
      }
      if (other.getMultiplierValue() != 0) {
        setMultiplierValue(other.getMultiplierValue());
      }
      if (other.getExplode() != false) {
        setExplode(other.getExplode());
      }
      if (!other.getExplodeWhen().isEmpty()) {
        explodeWhen_ = other.explodeWhen_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getExplodeValue() != 0) {
        setExplodeValue(other.getExplodeValue());
      }
      if (other.getModifyScore() != false) {
        setModifyScore(other.getModifyScore());
      }
      if (other.getModifyScoreValue() != 0) {
        setModifyScoreValue(other.getModifyScoreValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              epoch_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer m =
                  input.readMessage(
                      com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.parser(),
                      extensionRegistry);
              if (sideBuilder_ == null) {
                ensureSideIsMutable();
                side_.add(m);
              } else {
                sideBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              titleStringsId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              colour_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              selected_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              multiplier_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              multiplierValue_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              explode_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              explodeWhen_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              explodeValue_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              modifyScore_ = input.readBool();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              modifyScoreValue_ = input.readInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long epoch_ ;
    /**
     * <code>int64 epoch = 1;</code>
     * @return The epoch.
     */
    @java.lang.Override
    public long getEpoch() {
      return epoch_;
    }
    /**
     * <code>int64 epoch = 1;</code>
     * @param value The epoch to set.
     * @return This builder for chaining.
     */
    public Builder setEpoch(long value) {

      epoch_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 epoch = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpoch() {
      bitField0_ = (bitField0_ & ~0x00000001);
      epoch_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer> side_ =
      java.util.Collections.emptyList();
    private void ensureSideIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        side_ = new java.util.ArrayList<com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer>(side_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder> sideBuilder_;

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public java.util.List<com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer> getSideList() {
      if (sideBuilder_ == null) {
        return java.util.Collections.unmodifiableList(side_);
      } else {
        return sideBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public int getSideCount() {
      if (sideBuilder_ == null) {
        return side_.size();
      } else {
        return sideBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer getSide(int index) {
      if (sideBuilder_ == null) {
        return side_.get(index);
      } else {
        return sideBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder setSide(
        int index, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer value) {
      if (sideBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSideIsMutable();
        side_.set(index, value);
        onChanged();
      } else {
        sideBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder setSide(
        int index, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder builderForValue) {
      if (sideBuilder_ == null) {
        ensureSideIsMutable();
        side_.set(index, builderForValue.build());
        onChanged();
      } else {
        sideBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder addSide(com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer value) {
      if (sideBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSideIsMutable();
        side_.add(value);
        onChanged();
      } else {
        sideBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder addSide(
        int index, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer value) {
      if (sideBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSideIsMutable();
        side_.add(index, value);
        onChanged();
      } else {
        sideBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder addSide(
        com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder builderForValue) {
      if (sideBuilder_ == null) {
        ensureSideIsMutable();
        side_.add(builderForValue.build());
        onChanged();
      } else {
        sideBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder addSide(
        int index, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder builderForValue) {
      if (sideBuilder_ == null) {
        ensureSideIsMutable();
        side_.add(index, builderForValue.build());
        onChanged();
      } else {
        sideBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder addAllSide(
        java.lang.Iterable<? extends com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer> values) {
      if (sideBuilder_ == null) {
        ensureSideIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, side_);
        onChanged();
      } else {
        sideBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder clearSide() {
      if (sideBuilder_ == null) {
        side_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        sideBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public Builder removeSide(int index) {
      if (sideBuilder_ == null) {
        ensureSideIsMutable();
        side_.remove(index);
        onChanged();
      } else {
        sideBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder getSideBuilder(
        int index) {
      return getSideFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder getSideOrBuilder(
        int index) {
      if (sideBuilder_ == null) {
        return side_.get(index);  } else {
        return sideBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public java.util.List<? extends com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder> 
         getSideOrBuilderList() {
      if (sideBuilder_ != null) {
        return sideBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(side_);
      }
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder addSideBuilder() {
      return getSideFieldBuilder().addBuilder(
          com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder addSideBuilder(
        int index) {
      return getSideFieldBuilder().addBuilder(
          index, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer side = 2;</code>
     */
    public java.util.List<com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder> 
         getSideBuilderList() {
      return getSideFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder> 
        getSideFieldBuilder() {
      if (sideBuilder_ == null) {
        sideBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBuffer.Builder, com.github.jameshnsears.chance.data.domain.proto.SideProtocolBufferOrBuilder>(
                side_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        side_ = null;
      }
      return sideBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int titleStringsId_ ;
    /**
     * <code>int32 titleStringsId = 4;</code>
     * @return The titleStringsId.
     */
    @java.lang.Override
    public int getTitleStringsId() {
      return titleStringsId_;
    }
    /**
     * <code>int32 titleStringsId = 4;</code>
     * @param value The titleStringsId to set.
     * @return This builder for chaining.
     */
    public Builder setTitleStringsId(int value) {

      titleStringsId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 titleStringsId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitleStringsId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      titleStringsId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object colour_ = "";
    /**
     * <code>string colour = 5;</code>
     * @return The colour.
     */
    public java.lang.String getColour() {
      java.lang.Object ref = colour_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        colour_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string colour = 5;</code>
     * @return The bytes for colour.
     */
    public com.google.protobuf.ByteString
        getColourBytes() {
      java.lang.Object ref = colour_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string colour = 5;</code>
     * @param value The colour to set.
     * @return This builder for chaining.
     */
    public Builder setColour(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      colour_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string colour = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColour() {
      colour_ = getDefaultInstance().getColour();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string colour = 5;</code>
     * @param value The bytes for colour to set.
     * @return This builder for chaining.
     */
    public Builder setColourBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      colour_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean selected_ ;
    /**
     * <code>bool selected = 6;</code>
     * @return The selected.
     */
    @java.lang.Override
    public boolean getSelected() {
      return selected_;
    }
    /**
     * <code>bool selected = 6;</code>
     * @param value The selected to set.
     * @return This builder for chaining.
     */
    public Builder setSelected(boolean value) {

      selected_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool selected = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelected() {
      bitField0_ = (bitField0_ & ~0x00000020);
      selected_ = false;
      onChanged();
      return this;
    }

    private boolean multiplier_ ;
    /**
     * <code>bool multiplier = 7;</code>
     * @return The multiplier.
     */
    @java.lang.Override
    public boolean getMultiplier() {
      return multiplier_;
    }
    /**
     * <code>bool multiplier = 7;</code>
     * @param value The multiplier to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplier(boolean value) {

      multiplier_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool multiplier = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMultiplier() {
      bitField0_ = (bitField0_ & ~0x00000040);
      multiplier_ = false;
      onChanged();
      return this;
    }

    private int multiplierValue_ ;
    /**
     * <code>int32 multiplierValue = 8;</code>
     * @return The multiplierValue.
     */
    @java.lang.Override
    public int getMultiplierValue() {
      return multiplierValue_;
    }
    /**
     * <code>int32 multiplierValue = 8;</code>
     * @param value The multiplierValue to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplierValue(int value) {

      multiplierValue_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 multiplierValue = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMultiplierValue() {
      bitField0_ = (bitField0_ & ~0x00000080);
      multiplierValue_ = 0;
      onChanged();
      return this;
    }

    private boolean explode_ ;
    /**
     * <code>bool explode = 9;</code>
     * @return The explode.
     */
    @java.lang.Override
    public boolean getExplode() {
      return explode_;
    }
    /**
     * <code>bool explode = 9;</code>
     * @param value The explode to set.
     * @return This builder for chaining.
     */
    public Builder setExplode(boolean value) {

      explode_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bool explode = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearExplode() {
      bitField0_ = (bitField0_ & ~0x00000100);
      explode_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object explodeWhen_ = "";
    /**
     * <code>string explodeWhen = 10;</code>
     * @return The explodeWhen.
     */
    public java.lang.String getExplodeWhen() {
      java.lang.Object ref = explodeWhen_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        explodeWhen_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string explodeWhen = 10;</code>
     * @return The bytes for explodeWhen.
     */
    public com.google.protobuf.ByteString
        getExplodeWhenBytes() {
      java.lang.Object ref = explodeWhen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        explodeWhen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string explodeWhen = 10;</code>
     * @param value The explodeWhen to set.
     * @return This builder for chaining.
     */
    public Builder setExplodeWhen(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      explodeWhen_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string explodeWhen = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearExplodeWhen() {
      explodeWhen_ = getDefaultInstance().getExplodeWhen();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string explodeWhen = 10;</code>
     * @param value The bytes for explodeWhen to set.
     * @return This builder for chaining.
     */
    public Builder setExplodeWhenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      explodeWhen_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private int explodeValue_ ;
    /**
     * <code>int32 explodeValue = 11;</code>
     * @return The explodeValue.
     */
    @java.lang.Override
    public int getExplodeValue() {
      return explodeValue_;
    }
    /**
     * <code>int32 explodeValue = 11;</code>
     * @param value The explodeValue to set.
     * @return This builder for chaining.
     */
    public Builder setExplodeValue(int value) {

      explodeValue_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 explodeValue = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearExplodeValue() {
      bitField0_ = (bitField0_ & ~0x00000400);
      explodeValue_ = 0;
      onChanged();
      return this;
    }

    private boolean modifyScore_ ;
    /**
     * <code>bool modifyScore = 12;</code>
     * @return The modifyScore.
     */
    @java.lang.Override
    public boolean getModifyScore() {
      return modifyScore_;
    }
    /**
     * <code>bool modifyScore = 12;</code>
     * @param value The modifyScore to set.
     * @return This builder for chaining.
     */
    public Builder setModifyScore(boolean value) {

      modifyScore_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>bool modifyScore = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifyScore() {
      bitField0_ = (bitField0_ & ~0x00000800);
      modifyScore_ = false;
      onChanged();
      return this;
    }

    private int modifyScoreValue_ ;
    /**
     * <code>int32 modifyScoreValue = 13;</code>
     * @return The modifyScoreValue.
     */
    @java.lang.Override
    public int getModifyScoreValue() {
      return modifyScoreValue_;
    }
    /**
     * <code>int32 modifyScoreValue = 13;</code>
     * @param value The modifyScoreValue to set.
     * @return This builder for chaining.
     */
    public Builder setModifyScoreValue(int value) {

      modifyScoreValue_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 modifyScoreValue = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifyScoreValue() {
      bitField0_ = (bitField0_ & ~0x00001000);
      modifyScoreValue_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer)
  }

  // @@protoc_insertion_point(class_scope:com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer)
  private static final com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer();
  }

  public static com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiceProtocolBuffer>
      PARSER = new com.google.protobuf.AbstractParser<DiceProtocolBuffer>() {
    @java.lang.Override
    public DiceProtocolBuffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DiceProtocolBuffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiceProtocolBuffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.jameshnsears.chance.data.domain.proto.DiceProtocolBuffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

