// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice_bag.proto

// Protobuf Java Version: 3.25.3
package com.github.jameshnsears.chance.data.domain.proto;

public final class DiceBag {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceBagProtocolBuffer_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceBagProtocolBuffer_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016dice_bag.proto\0220com.github.jameshnsear" +
                        "s.chance.data.domain.proto\032\ndice.proto\"k" +
                        "\n\025DiceBagProtocolBuffer\022R\n\004dice\030\001 \003(\0132D." +
                        "com.github.jameshnsears.chance.data.doma" +
                        "in.proto.DiceProtocolBufferB\002P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.github.jameshnsears.chance.data.domain.proto.Dice.getDescriptor(),
                        });
        internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceBagProtocolBuffer_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceBagProtocolBuffer_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_github_jameshnsears_chance_data_domain_proto_DiceBagProtocolBuffer_descriptor,
                new java.lang.String[]{"Dice",});
        com.github.jameshnsears.chance.data.domain.proto.Dice.getDescriptor();
    }

    private DiceBag() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
