// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: roll_history.proto
// Protobuf Java Version: 4.28.2

package com.github.jameshnsears.chance.data.domain.proto;

public interface RollListProtocolBufferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.domain.proto.RollListProtocolBuffer)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer roll = 1;</code>
     */
    java.util.List<com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer>
    getRollList();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer roll = 1;</code>
     */
    com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer getRoll(int index);

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer roll = 1;</code>
     */
    int getRollCount();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer roll = 1;</code>
     */
    java.util.List<? extends com.github.jameshnsears.chance.data.domain.proto.RollProtocolBufferOrBuilder>
    getRollOrBuilderList();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.domain.proto.RollProtocolBuffer roll = 1;</code>
     */
    com.github.jameshnsears.chance.data.domain.proto.RollProtocolBufferOrBuilder getRollOrBuilder(
        int index);
}
