// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 3.25.3
package com.github.jameshnsears.chance.data.domain.proto;

public interface SettingsProtocolBufferOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.domain.proto.SettingsProtocolBuffer)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 tabRowChance = 1;</code>
     *
     * @return The tabRowChance.
     */
    int getTabRowChance();

    /**
     * <code>float resize = 2;</code>
     *
     * @return The resize.
     */
    float getResize();

    /**
     * <code>bool rollIndexTime = 3;</code>
     *
     * @return The rollIndexTime.
     */
    boolean getRollIndexTime();

    /**
     * <code>bool rollScore = 4;</code>
     *
     * @return The rollScore.
     */
    boolean getRollScore();

    /**
     * <code>bool diceTitle = 5;</code>
     *
     * @return The diceTitle.
     */
    boolean getDiceTitle();

    /**
     * <code>bool sideNumber = 6;</code>
     *
     * @return The sideNumber.
     */
    boolean getSideNumber();

    /**
     * <code>bool behaviour = 7;</code>
     *
     * @return The behaviour.
     */
    boolean getBehaviour();

    /**
     * <code>bool sideDescription = 8;</code>
     *
     * @return The sideDescription.
     */
    boolean getSideDescription();

    /**
     * <code>bool sideSVG = 9;</code>
     *
     * @return The sideSVG.
     */
    boolean getSideSVG();

    /**
     * <code>bool rollSound = 10;</code>
     *
     * @return The rollSound.
     */
    boolean getRollSound();
}
