// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: side.proto

// Protobuf Java Version: 3.25.1
package com.github.jameshnsears.chance.data.domain.proto;

public final class Side {
  private Side() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_jameshnsears_chance_data_domain_proto_SideProtocolBuffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_jameshnsears_chance_data_domain_proto_SideProtocolBuffer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nside.proto\0220com.github.jameshnsears.ch" +
      "ance.data.domain.proto\"\266\001\n\022SideProtocolB" +
      "uffer\022\016\n\006number\030\001 \001(\005\022\024\n\014numberColour\030\002 " +
      "\001(\t\022\023\n\013imageBase64\030\003 \001(\t\022\027\n\017imageDrawabl" +
      "eId\030\004 \001(\005\022\023\n\013description\030\005 \001(\t\022\034\n\024descri" +
      "ptionStringsId\030\006 \001(\005\022\031\n\021descriptionColou" +
      "r\030\007 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_jameshnsears_chance_data_domain_proto_SideProtocolBuffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_jameshnsears_chance_data_domain_proto_SideProtocolBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_jameshnsears_chance_data_domain_proto_SideProtocolBuffer_descriptor,
        new java.lang.String[] { "Number", "NumberColour", "ImageBase64", "ImageDrawableId", "Description", "DescriptionStringsId", "DescriptionColour", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
