ignore:
  - "**/*Preview.kt"
  - "**/test/**"
  - "**/androidTest/**"
  - "**/testDebug/**"
  - "**/testRelease/**"
  - "**/build/**"
  - "module/data-repo-impl/src/main/java/**"

flags:
  app-androidTest:
    carryforward: false

  data-common-androidTest:
    carryforward: false

  data-common-unitTest:
    carryforward: false

  data-repo-api-unitTest:
    carryforward: false

  ui-androidTest:
    carryforward: false

  ui-unitTest:
    carryforward: false
