ignore:
  - "module/data/src/main/java"
  - "**/*Preview.kt"

flags:
  app.androidTest:
    carryforward: false

  data.test:
    carryforward: false
  data.androidTest:
    carryforward: false

  ui.test:
    carryforward: false

  ui-dialog-bag.test:
    carryforward: false
  ui-dialog-bag.androidTest:
    carryforward: false
