// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: group.proto
// Protobuf Java Version: 4.28.2

package com.github.jameshnsears.chance.data.domain.proto;

public interface GroupProtocolBufferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     *
     * @return The uuid.
     */
    java.lang.String getUuid();

    /**
     * <code>string uuid = 1;</code>
     *
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
    getUuidBytes();

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @return A list containing the uuidDice.
     */
    java.util.List<java.lang.String>
    getUuidDiceList();

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @return The count of uuidDice.
     */
    int getUuidDiceCount();

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The uuidDice at the given index.
     */
    java.lang.String getUuidDice(int index);

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the uuidDice at the given index.
     */
    com.google.protobuf.ByteString
    getUuidDiceBytes(int index);

    /**
     * <code>string notes = 4;</code>
     *
     * @return The notes.
     */
    java.lang.String getNotes();

    /**
     * <code>string notes = 4;</code>
     *
     * @return The bytes for notes.
     */
    com.google.protobuf.ByteString
    getNotesBytes();

    /**
     * <code>int32 displayIndex = 5;</code>
     *
     * @return The displayIndex.
     */
    int getDisplayIndex();

    /**
     * <code>bool selected = 6;</code>
     *
     * @return The selected.
     */
    boolean getSelected();
}
