// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: group.proto
// Protobuf Java Version: 4.28.2

package com.github.jameshnsears.chance.data.domain.proto;

/**
 * Protobuf type {@code com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer}
 */
public final class GroupProtocolBuffer extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer)
    GroupProtocolBufferOrBuilder {
    public static final int UUID_FIELD_NUMBER = 1;
    public static final int NAME_FIELD_NUMBER = 2;
    public static final int UUIDDICE_FIELD_NUMBER = 3;
    public static final int NOTES_FIELD_NUMBER = 4;
    public static final int DISPLAYINDEX_FIELD_NUMBER = 5;
    public static final int SELECTED_FIELD_NUMBER = 6;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer)
    private static final com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<GroupProtocolBuffer>
        PARSER = new com.google.protobuf.AbstractParser<GroupProtocolBuffer>() {
        @java.lang.Override
        public GroupProtocolBuffer parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                    .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */ 4,
            /* minor= */ 28,
            /* patch= */ 2,
            /* suffix= */ "",
            GroupProtocolBuffer.class.getName());
    }

    static {
        DEFAULT_INSTANCE = new com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer();
    }

    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList uuidDice_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    @SuppressWarnings("serial")
    private volatile java.lang.Object notes_ = "";
    private int displayIndex_ = 0;
    private boolean selected_ = false;
    private byte memoizedIsInitialized = -1;

    // Use GroupProtocolBuffer.newBuilder() to construct.
    private GroupProtocolBuffer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private GroupProtocolBuffer() {
        uuid_ = "";
        name_ = "";
        uuidDice_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        notes_ = "";
    }

    public static com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.github.jameshnsears.chance.data.domain.proto.Group.internal_static_com_github_jameshnsears_chance_data_domain_proto_GroupProtocolBuffer_descriptor;
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<GroupProtocolBuffer> parser() {
        return PARSER;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.github.jameshnsears.chance.data.domain.proto.Group.internal_static_com_github_jameshnsears_chance_data_domain_proto_GroupProtocolBuffer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.class, com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.Builder.class);
    }

    /**
     * <code>string uuid = 1;</code>
     *
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
        }
    }

    /**
     * <code>string uuid = 1;</code>
     *
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uuid_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @return A list containing the uuidDice.
     */
    public com.google.protobuf.ProtocolStringList
    getUuidDiceList() {
        return uuidDice_;
    }

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @return The count of uuidDice.
     */
    public int getUuidDiceCount() {
        return uuidDice_.size();
    }

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The uuidDice at the given index.
     */
    public java.lang.String getUuidDice(int index) {
        return uuidDice_.get(index);
    }

    /**
     * <code>repeated string uuidDice = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the uuidDice at the given index.
     */
    public com.google.protobuf.ByteString
    getUuidDiceBytes(int index) {
        return uuidDice_.getByteString(index);
    }

    /**
     * <code>string notes = 4;</code>
     *
     * @return The notes.
     */
    @java.lang.Override
    public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            notes_ = s;
            return s;
        }
    }

    /**
     * <code>string notes = 4;</code>
     *
     * @return The bytes for notes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            notes_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>int32 displayIndex = 5;</code>
     *
     * @return The displayIndex.
     */
    @java.lang.Override
    public int getDisplayIndex() {
        return displayIndex_;
    }

    /**
     * <code>bool selected = 6;</code>
     *
     * @return The selected.
     */
    @java.lang.Override
    public boolean getSelected() {
        return selected_;
    }

    @java.lang.Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, uuid_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
        }
        for (int i = 0; i < uuidDice_.size(); i++) {
            com.google.protobuf.GeneratedMessage.writeString(output, 3, uuidDice_.getRaw(i));
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notes_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 4, notes_);
        }
        if (displayIndex_ != 0) {
            output.writeInt32(5, displayIndex_);
        }
        if (selected_) {
            output.writeBool(6, selected_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uuid_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < uuidDice_.size(); i++) {
                dataSize += computeStringSizeNoTag(uuidDice_.getRaw(i));
            }
            size += dataSize;
            size += getUuidDiceList().size();
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notes_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(4, notes_);
        }
        if (displayIndex_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(5, displayIndex_);
        }
        if (selected_) {
            size += com.google.protobuf.CodedOutputStream
                .computeBoolSize(6, selected_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof GroupProtocolBuffer other)) {
            return super.equals(obj);
        }

        if (!getUuid()
            .equals(other.getUuid())) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!getUuidDiceList()
            .equals(other.getUuidDiceList())) return false;
        if (!getNotes()
            .equals(other.getNotes())) return false;
        if (getDisplayIndex()
            != other.getDisplayIndex()) return false;
        if (getSelected()
            != other.getSelected()) return false;
        return getUnknownFields().equals(other.getUnknownFields());
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        if (getUuidDiceCount() > 0) {
            hash = (37 * hash) + UUIDDICE_FIELD_NUMBER;
            hash = (53 * hash) + getUuidDiceList().hashCode();
        }
        hash = (37 * hash) + NOTES_FIELD_NUMBER;
        hash = (53 * hash) + getNotes().hashCode();
        hash = (37 * hash) + DISPLAYINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getDisplayIndex();
        hash = (37 * hash) + SELECTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSelected());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupProtocolBuffer> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer)
        com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBufferOrBuilder {
        private int bitField0_;
        private java.lang.Object uuid_ = "";
        private java.lang.Object name_ = "";
        private com.google.protobuf.LazyStringArrayList uuidDice_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        private java.lang.Object notes_ = "";
        private int displayIndex_;
        private boolean selected_;

        // Construct using com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.jameshnsears.chance.data.domain.proto.Group.internal_static_com_github_jameshnsears_chance_data_domain_proto_GroupProtocolBuffer_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.jameshnsears.chance.data.domain.proto.Group.internal_static_com_github_jameshnsears_chance_data_domain_proto_GroupProtocolBuffer_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.class, com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            uuid_ = "";
            name_ = "";
            uuidDice_ =
                com.google.protobuf.LazyStringArrayList.emptyList();
            notes_ = "";
            displayIndex_ = 0;
            selected_ = false;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.github.jameshnsears.chance.data.domain.proto.Group.internal_static_com_github_jameshnsears_chance_data_domain_proto_GroupProtocolBuffer_descriptor;
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer getDefaultInstanceForType() {
            return com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.getDefaultInstance();
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer build() {
            com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer buildPartial() {
            com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer result = new com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.uuid_ = uuid_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.name_ = name_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                uuidDice_.makeImmutable();
                result.uuidDice_ = uuidDice_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.notes_ = notes_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.displayIndex_ = displayIndex_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.selected_ = selected_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer) {
                return mergeFrom((com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer other) {
            if (other == com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer.getDefaultInstance()) return this;
            if (!other.getUuid().isEmpty()) {
                uuid_ = other.uuid_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.uuidDice_.isEmpty()) {
                if (uuidDice_.isEmpty()) {
                    uuidDice_ = other.uuidDice_;
                    bitField0_ |= 0x00000004;
                } else {
                    ensureUuidDiceIsMutable();
                    uuidDice_.addAll(other.uuidDice_);
                }
                onChanged();
            }
            if (!other.getNotes().isEmpty()) {
                notes_ = other.notes_;
                bitField0_ |= 0x00000008;
                onChanged();
            }
            if (other.getDisplayIndex() != 0) {
                setDisplayIndex(other.getDisplayIndex());
            }
            if (other.getSelected()) {
                setSelected(other.getSelected());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            uuid_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            name_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensureUuidDiceIsMutable();
                            uuidDice_.add(s);
                            break;
                        } // case 26
                        case 34: {
                            notes_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 34
                        case 40: {
                            displayIndex_ = input.readInt32();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 40
                        case 48: {
                            selected_ = input.readBool();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 48
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>string uuid = 1;</code>
         *
         * @return The uuid.
         */
        public java.lang.String getUuid() {
            java.lang.Object ref = uuid_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uuid_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string uuid = 1;</code>
         *
         * @param value The uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuid(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            uuid_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 1;</code>
         *
         * @return The bytes for uuid.
         */
        public com.google.protobuf.ByteString
        getUuidBytes() {
            java.lang.Object ref = uuid_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                uuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uuid = 1;</code>
         *
         * @param value The bytes for uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuidBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            uuid_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUuid() {
            uuid_ = getDefaultInstance().getUuid();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            name_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            name_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {
            name_ = getDefaultInstance().getName();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        private void ensureUuidDiceIsMutable() {
            if (!uuidDice_.isModifiable()) {
                uuidDice_ = new com.google.protobuf.LazyStringArrayList(uuidDice_);
            }
            bitField0_ |= 0x00000004;
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @return A list containing the uuidDice.
         */
        public com.google.protobuf.ProtocolStringList
        getUuidDiceList() {
            uuidDice_.makeImmutable();
            return uuidDice_;
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @return The count of uuidDice.
         */
        public int getUuidDiceCount() {
            return uuidDice_.size();
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The uuidDice at the given index.
         */
        public java.lang.String getUuidDice(int index) {
            return uuidDice_.get(index);
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the uuidDice at the given index.
         */
        public com.google.protobuf.ByteString
        getUuidDiceBytes(int index) {
            return uuidDice_.getByteString(index);
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @param index The index to set the value at.
         * @param value The uuidDice to set.
         * @return This builder for chaining.
         */
        public Builder setUuidDice(
            int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureUuidDiceIsMutable();
            uuidDice_.set(index, value);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @param value The uuidDice to add.
         * @return This builder for chaining.
         */
        public Builder addUuidDice(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureUuidDiceIsMutable();
            uuidDice_.add(value);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @param values The uuidDice to add.
         * @return This builder for chaining.
         */
        public Builder addAllUuidDice(
            java.lang.Iterable<java.lang.String> values) {
            ensureUuidDiceIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, uuidDice_);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUuidDice() {
            uuidDice_ =
                com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string uuidDice = 3;</code>
         *
         * @param value The bytes of the uuidDice to add.
         * @return This builder for chaining.
         */
        public Builder addUuidDiceBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureUuidDiceIsMutable();
            uuidDice_.add(value);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>string notes = 4;</code>
         *
         * @return The notes.
         */
        public java.lang.String getNotes() {
            java.lang.Object ref = notes_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                notes_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string notes = 4;</code>
         *
         * @param value The notes to set.
         * @return This builder for chaining.
         */
        public Builder setNotes(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            notes_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>string notes = 4;</code>
         *
         * @return The bytes for notes.
         */
        public com.google.protobuf.ByteString
        getNotesBytes() {
            java.lang.Object ref = notes_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                notes_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string notes = 4;</code>
         *
         * @param value The bytes for notes to set.
         * @return This builder for chaining.
         */
        public Builder setNotesBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            notes_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>string notes = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearNotes() {
            notes_ = getDefaultInstance().getNotes();
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
            return this;
        }

        /**
         * <code>int32 displayIndex = 5;</code>
         *
         * @return The displayIndex.
         */
        @java.lang.Override
        public int getDisplayIndex() {
            return displayIndex_;
        }

        /**
         * <code>int32 displayIndex = 5;</code>
         *
         * @param value The displayIndex to set.
         * @return This builder for chaining.
         */
        public Builder setDisplayIndex(int value) {

            displayIndex_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>int32 displayIndex = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDisplayIndex() {
            bitField0_ = (bitField0_ & ~0x00000010);
            displayIndex_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>bool selected = 6;</code>
         *
         * @return The selected.
         */
        @java.lang.Override
        public boolean getSelected() {
            return selected_;
        }

        /**
         * <code>bool selected = 6;</code>
         *
         * @param value The selected to set.
         * @return This builder for chaining.
         */
        public Builder setSelected(boolean value) {

            selected_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>bool selected = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSelected() {
            bitField0_ = (bitField0_ & ~0x00000020);
            selected_ = false;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.github.jameshnsears.chance.data.domain.proto.GroupProtocolBuffer)
    }

}

