// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: settings.proto
// Protobuf Java Version: 4.28.2

package com.github.jameshnsears.chance.data.domain.proto;

public interface SettingsProtocolBufferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.domain.proto.SettingsProtocolBuffer)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 resize = 1 [deprecated = true];</code>
     *
     * @return The resize.
     * @deprecated com.github.jameshnsears.chance.data.domain.proto.SettingsProtocolBuffer.resize is deprecated.
     * See settings.proto;l=7
     */
    @java.lang.Deprecated
    int getResize();

    /**
     * <code>bool rollIndexTime = 2;</code>
     *
     * @return The rollIndexTime.
     */
    boolean getRollIndexTime();

    /**
     * <code>bool rollScore = 3;</code>
     *
     * @return The rollScore.
     */
    boolean getRollScore();

    /**
     * <code>bool diceTitle = 4;</code>
     *
     * @return The diceTitle.
     */
    boolean getDiceTitle();

    /**
     * <code>bool sideNumber = 5;</code>
     *
     * @return The sideNumber.
     */
    boolean getSideNumber();

    /**
     * <code>bool behaviour = 6;</code>
     *
     * @return The behaviour.
     */
    boolean getBehaviour();

    /**
     * <code>bool sideDescription = 7;</code>
     *
     * @return The sideDescription.
     */
    boolean getSideDescription();

    /**
     * <code>bool sideSVG = 8;</code>
     *
     * @return The sideSVG.
     */
    boolean getSideSVG();

    /**
     * <code>bool rollSound = 9;</code>
     *
     * @return The rollSound.
     */
    boolean getRollSound();

    /**
     * <code>bool shuffle = 10;</code>
     *
     * @return The shuffle.
     */
    boolean getShuffle();

    /**
     * <code>bool haptics = 11;</code>
     *
     * @return The haptics.
     */
    boolean getHaptics();

    /**
     * <code>bool rollScoreTTS = 12;</code>
     *
     * @return The rollScoreTTS.
     */
    boolean getRollScoreTTS();

    /**
     * <code>bool shakeToRoll = 13;</code>
     *
     * @return The shakeToRoll.
     */
    boolean getShakeToRoll();

    /**
     * <code>float resizeZoom = 14;</code>
     *
     * @return The resizeZoom.
     */
    float getResizeZoom();

    /**
     * <code>bool groupTitle = 15;</code>
     *
     * @return The groupTitle.
     */
    boolean getGroupTitle();

    /**
     * <code>bool history = 16;</code>
     *
     * @return The history.
     */
    boolean getHistory();
}
