version: 2.1

orbs:
  android: circleci/android@3.1.0
  codecov: codecov/codecov@4.1.0

android_exec: &android_exec
  name: android/android_machine
  resource_class: large
  tag: default

commands:
  codecov_upload:
    parameters:
      report_path:
        type: string
      flags:
        type: string
    steps:
      - codecov/upload:
          files: << parameters.report_path >>
          flags: << parameters.flags >>

  write_local_properties:
    steps:
      - run:
          name: Write local.properties
          command: |
            echo "sdk.dir=/android-sdk" > local.properties
            echo "maps_api_key=$MAPS_API_KEY" >> local.properties

  write_google_services:
    parameters:
      target_module:
        type: string
    steps:
      - run:
          name: Write google-services.json
          command: echo "$GOOGLE_SERVICES_JSON" > << parameters.target_module >>/google-services.json

  run_android_test:
    parameters:
      test_command:
        type: string
      report_path:
        type: string
      flags:
        type: string
    steps:
      - run:
          name: Run Android Test
          command: << parameters.test_command >>
      - codecov_upload:
          report_path: << parameters.report_path >>
          flags: << parameters.flags >>

  store_android_artifacts:
    parameters:
      module_path:
        type: string
    steps:
      - store_test_results:
          path: << parameters.module_path >>/build/test-results
      - store_artifacts:
          path: << parameters.module_path >>/build/reports

jobs:
  unit_test_ui:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: UI unit tests
          command: |
            ./gradlew :module:ui:jacocoFdroidTestReport \
              --parallel \
              --max-workers 2 \
              -Dorg.gradle.jvmargs="-Xmx2048m"
      - codecov_upload:
          report_path: ./module/ui/build/reports/jacoco/unitTest.xml
          flags: ui-unitTest
      - android/save_gradle_cache

  unit_test_data_repo_api:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: Data repo api unit tests
          command: |
            ./gradlew :module:data-repo-api:jacocoFdroidTestReport \
              --parallel \
              --max-workers 2 \
              -Dorg.gradle.jvmargs="-Xmx2048m"
      - codecov_upload:
          report_path: ./module/data-repo-api/build/reports/jacoco/unitTest.xml
          flags: data-repo-api-unitTest
      - android/save_gradle_cache

  unit_test_data_common:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: Data common unit tests
          command: |
            ./gradlew :module:data-common:jacocoFdroidTestReport \
              --parallel \
              --max-workers 2 \
              -Dorg.gradle.jvmargs="-Xmx2048m"
      - codecov_upload:
          report_path: ./module/data-common/build/reports/jacoco/unitTest.xml
          flags: data-common-unitTest
      - android/save_gradle_cache

  ui_android_test:
    executor: *android_exec
    steps:
      - checkout:
          submodules: true
      - android/create_avd:
          avd_name: testavd
          system_image: system-images;android-36;google_apis;x86_64
          install: true
      - write_local_properties
      - write_google_services:
          target_module: app
      - android/start_emulator:
          avd_name: testavd
          no_window: true
          gpu: swiftshader_indirect
          restore_gradle_cache_prefix: v1a
      - run_android_test:
          test_command: ./gradlew :module:ui:connectedFdroidDebugAndroidTest --continue --parallel -Dorg.gradle.jvmargs="-Xmx2048m"
          report_path: ./module/ui/build/reports/coverage/androidTest/fdroid/debug/connected/report.xml
          flags: ui-androidTest
      - store_android_artifacts:
          module_path: ./module/ui

  app_android_test:
    executor: *android_exec
    steps:
      - checkout:
          submodules: true
      - android/create_avd:
          avd_name: testavd
          system_image: system-images;android-36;google_apis;x86_64
          install: true
      - write_local_properties
      - write_google_services:
          target_module: app
      - android/start_emulator:
          avd_name: testavd
          no_window: true
          gpu: swiftshader_indirect
          restore_gradle_cache_prefix: v1a
      - run_android_test:
          test_command: ./gradlew :app:connectedFdroidDebugAndroidTest --continue --parallel -Dorg.gradle.jvmargs="-Xmx2048m"
          report_path: ./app/build/reports/coverage/androidTest/fdroid/debug/connected/report.xml
          flags: app-androidTest
      - store_android_artifacts:
          module_path: ./app

  data_common_android_test:
    executor: *android_exec
    steps:
      - checkout:
          submodules: true
      - android/create_avd:
          avd_name: testavd
          system_image: system-images;android-36;google_apis;x86_64
          install: true
      - write_local_properties
      - write_google_services:
          target_module: app
      - android/start_emulator:
          avd_name: testavd
          no_window: true
          gpu: swiftshader_indirect
          restore_gradle_cache_prefix: v1a
      - run_android_test:
          test_command: ./gradlew :module:data-common:connectedFdroidDebugAndroidTest --continue --parallel -Dorg.gradle.jvmargs="-Xmx2048m"
          report_path: ./module/data-common/build/reports/coverage/androidTest/fdroid/debug/connected/report.xml
          flags: data-common-androidTest
      - store_android_artifacts:
          module_path: ./module/data-common

  detekt:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dsonar.gradle.skipCompile=true"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: Detekt
          command: ./gradlew detekt --parallel
      - android/save_gradle_cache

  ktlint:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dsonar.gradle.skipCompile=true"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: Ktlint
          command: ./gradlew ktlintCheck --parallel
      - android/save_gradle_cache

  lint_fdroid_debug:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: Lint Fdroid Debug
          command: ./gradlew lintFdroidDebug --parallel
      - android/save_gradle_cache

  sonarqube:
    executor: *android_exec
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout:
          submodules: true
      - android/restore_gradle_cache
      - run:
          name: Sonarqube
          command: ./gradlew sonar -Dsonar.gradle.skipCompile=true
      - android/save_gradle_cache

workflows:
  codecov_and_static:
    jobs:
      - unit_test_ui
      - unit_test_data_repo_api
      - unit_test_data_common
      - ui_android_test
      - app_android_test
      - data_common_android_test
      - detekt
      - ktlint
      - lint_fdroid_debug
      - sonarqube
