[versions]
activity-compose = "1.8.2"
appcompat = "1.6.1"
coil-svg = "2.6.0"
colorpicker-compose = "1.0.7"
com-android-application = "8.3.1"
com-android-library = "8.3.1"
com-diffplug-spotless = "6.25.0"
compose-bom = "2024.02.02"
core-ktx = "1.12.0"
datastore-core = "1.0.0"
espresso-core = "3.5.1"
io-gitlab-arturbosch-detekt = "1.23.6"
jackson-module-kotlin = "2.17.0"
json-kotlin-schema = "0.47"
jsonschema-generator = "4.34.0"
junit = "1.1.5"
junit-bom = "5.10.2"
junit-jupiter = "5.10.2"
kotlinx-coroutines-test = "1.8.0"
leakcanary-android = "2.13"
lifecycle-runtime-compose = "2.7.0"
lifecycle-viewmodel-compose = "2.7.0"
lifecycle-runtime-ktx = "2.7.0"
material = "1.11.0"
mockk = "1.13.10"
org-jetbrains-kotlin-android = "1.9.22"
org-jlleitschuh-gradle-ktlint = "12.1.0"
#noinspection GradleDependency
protobuf-java = "3.25.3"            # stay on 3.25.3
#noinspection GradleDependency
protobuf-java-util = "3.25.3"       # stay on 3.25.3
#noinspection GradleDependency
protobuf-kotlin = "3.25.3"          # stay on 3.25.3

slf4j-simple = "2.0.12"
timber = "5.0.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore-core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-svg" }
coil = { module = "io.coil-kt:coil", version.ref = "coil-svg" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil-svg" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker-compose" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
json-kotlin-schema = { module = "net.pwall.json:json-kotlin-schema", version.ref = "json-kotlin-schema" }
jsonschema-generator = { module = "com.github.victools:jsonschema-generator", version.ref = "jsonschema-generator" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
org-jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
org-junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
org-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf-java-util" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf-kotlin" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
com-android-library = { id = "com.android.library", version.ref = "com-android-library" }
com-diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "com-diffplug-spotless" }
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "io-gitlab-arturbosch-detekt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "org-jlleitschuh-gradle-ktlint" }
