// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dice.proto

// Protobuf Java Version: 3.25.1
package com.github.jameshnsears.chance.data.protocolbuffer;

/**
 * Protobuf type {@code com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer}
 */
public final class DiceProtocolBuffer extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer)
        DiceProtocolBufferOrBuilder {
    public static final int EPOCH_FIELD_NUMBER = 1;
    public static final int SIDE_FIELD_NUMBER = 2;
    public static final int TITLE_FIELD_NUMBER = 3;
    public static final int TITLESTRINGSID_FIELD_NUMBER = 4;
    public static final int COLOUR_FIELD_NUMBER = 5;
    public static final int SELECTED_FIELD_NUMBER = 6;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer)
    private static final com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<DiceProtocolBuffer>
            PARSER = new com.google.protobuf.AbstractParser<DiceProtocolBuffer>() {
        @java.lang.Override
        public DiceProtocolBuffer parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        DEFAULT_INSTANCE = new com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer();
    }

    private long epoch_ = 0L;
    @SuppressWarnings("serial")
    private java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer> side_;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    private int titleStringsId_ = 0;
    @SuppressWarnings("serial")
    private volatile java.lang.Object colour_ = "";
    private boolean selected_ = false;
    private byte memoizedIsInitialized = -1;

    // Use DiceProtocolBuffer.newBuilder() to construct.
    private DiceProtocolBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private DiceProtocolBuffer() {
        side_ = java.util.Collections.emptyList();
        title_ = "";
        colour_ = "";
    }

    public static com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.github.jameshnsears.chance.data.protocolbuffer.Dice.internal_static_com_github_jameshnsears_chance_data_protocolbuffer_DiceProtocolBuffer_descriptor;
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<DiceProtocolBuffer> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new DiceProtocolBuffer();
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.github.jameshnsears.chance.data.protocolbuffer.Dice.internal_static_com_github_jameshnsears_chance_data_protocolbuffer_DiceProtocolBuffer_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.class, com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.Builder.class);
    }

    /**
     * <code>uint64 epoch = 1;</code>
     *
     * @return The epoch.
     */
    @java.lang.Override
    public long getEpoch() {
        return epoch_;
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer> getSideList() {
        return side_;
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder>
    getSideOrBuilderList() {
        return side_;
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
     */
    @java.lang.Override
    public int getSideCount() {
        return side_.size();
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
     */
    @java.lang.Override
    public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer getSide(int index) {
        return side_.get(index);
    }

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
     */
    @java.lang.Override
    public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder getSideOrBuilder(
            int index) {
        return side_.get(index);
    }

    /**
     * <code>string title = 3;</code>
     *
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            title_ = s;
            return s;
        }
    }

    /**
     * <code>string title = 3;</code>
     *
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            title_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>int32 titleStringsId = 4;</code>
     *
     * @return The titleStringsId.
     */
    @java.lang.Override
    public int getTitleStringsId() {
        return titleStringsId_;
    }

    /**
     * <code>string colour = 5;</code>
     *
     * @return The colour.
     */
    @java.lang.Override
    public java.lang.String getColour() {
        java.lang.Object ref = colour_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            colour_ = s;
            return s;
        }
    }

    /**
     * <code>string colour = 5;</code>
     *
     * @return The bytes for colour.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getColourBytes() {
        java.lang.Object ref = colour_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            colour_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>bool selected = 6;</code>
     *
     * @return The selected.
     */
    @java.lang.Override
    public boolean getSelected() {
        return selected_;
    }

    @java.lang.Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (epoch_ != 0L) {
            output.writeUInt64(1, epoch_);
        }
        for (int i = 0; i < side_.size(); i++) {
            output.writeMessage(2, side_.get(i));
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
        }
        if (titleStringsId_ != 0) {
            output.writeInt32(4, titleStringsId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colour_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, colour_);
        }
        if (selected_) {
            output.writeBool(6, selected_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (epoch_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(1, epoch_);
        }
        for (int i = 0; i < side_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, side_.get(i));
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
        }
        if (titleStringsId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, titleStringsId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colour_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, colour_);
        }
        if (selected_) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(6, selected_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof DiceProtocolBuffer other)) {
            return super.equals(obj);
        }

        if (getEpoch()
                != other.getEpoch()) return false;
        if (!getSideList()
                .equals(other.getSideList())) return false;
        if (!getTitle()
                .equals(other.getTitle())) return false;
        if (getTitleStringsId()
                != other.getTitleStringsId()) return false;
        if (!getColour()
                .equals(other.getColour())) return false;
        if (getSelected()
                != other.getSelected()) return false;
        return getUnknownFields().equals(other.getUnknownFields());
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + EPOCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getEpoch());
        if (getSideCount() > 0) {
            hash = (37 * hash) + SIDE_FIELD_NUMBER;
            hash = (53 * hash) + getSideList().hashCode();
        }
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
        hash = (37 * hash) + TITLESTRINGSID_FIELD_NUMBER;
        hash = (53 * hash) + getTitleStringsId();
        hash = (37 * hash) + COLOUR_FIELD_NUMBER;
        hash = (53 * hash) + getColour().hashCode();
        hash = (37 * hash) + SELECTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSelected());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiceProtocolBuffer> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer)
            com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBufferOrBuilder {
        private int bitField0_;
        private long epoch_;
        private java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer> side_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder> sideBuilder_;
        private java.lang.Object title_ = "";
        private int titleStringsId_;
        private java.lang.Object colour_ = "";
        private boolean selected_;

        // Construct using com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.jameshnsears.chance.data.protocolbuffer.Dice.internal_static_com_github_jameshnsears_chance_data_protocolbuffer_DiceProtocolBuffer_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.jameshnsears.chance.data.protocolbuffer.Dice.internal_static_com_github_jameshnsears_chance_data_protocolbuffer_DiceProtocolBuffer_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.class, com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            epoch_ = 0L;
            if (sideBuilder_ == null) {
                side_ = java.util.Collections.emptyList();
            } else {
                side_ = null;
                sideBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            title_ = "";
            titleStringsId_ = 0;
            colour_ = "";
            selected_ = false;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.github.jameshnsears.chance.data.protocolbuffer.Dice.internal_static_com_github_jameshnsears_chance_data_protocolbuffer_DiceProtocolBuffer_descriptor;
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer getDefaultInstanceForType() {
            return com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.getDefaultInstance();
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer build() {
            com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer buildPartial() {
            com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer result = new com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer result) {
            if (sideBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    side_ = java.util.Collections.unmodifiableList(side_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.side_ = side_;
            } else {
                result.side_ = sideBuilder_.build();
            }
        }

        private void buildPartial0(com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.epoch_ = epoch_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.title_ = title_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.titleStringsId_ = titleStringsId_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.colour_ = colour_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.selected_ = selected_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer) {
                return mergeFrom((com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer other) {
            if (other == com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer.getDefaultInstance())
                return this;
            if (other.getEpoch() != 0L) {
                setEpoch(other.getEpoch());
            }
            if (sideBuilder_ == null) {
                if (!other.side_.isEmpty()) {
                    if (side_.isEmpty()) {
                        side_ = other.side_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureSideIsMutable();
                        side_.addAll(other.side_);
                    }
                    onChanged();
                }
            } else {
                if (!other.side_.isEmpty()) {
                    if (sideBuilder_.isEmpty()) {
                        sideBuilder_.dispose();
                        sideBuilder_ = null;
                        side_ = other.side_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        sideBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getSideFieldBuilder() : null;
                    } else {
                        sideBuilder_.addAllMessages(other.side_);
                    }
                }
            }
            if (!other.getTitle().isEmpty()) {
                title_ = other.title_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            if (other.getTitleStringsId() != 0) {
                setTitleStringsId(other.getTitleStringsId());
            }
            if (!other.getColour().isEmpty()) {
                colour_ = other.colour_;
                bitField0_ |= 0x00000010;
                onChanged();
            }
            if (other.getSelected()) {
                setSelected(other.getSelected());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            epoch_ = input.readUInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 18: {
                            com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer m =
                                    input.readMessage(
                                            com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.parser(),
                                            extensionRegistry);
                            if (sideBuilder_ == null) {
                                ensureSideIsMutable();
                                side_.add(m);
                            } else {
                                sideBuilder_.addMessage(m);
                            }
                            break;
                        } // case 18
                        case 26: {
                            title_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        case 32: {
                            titleStringsId_ = input.readInt32();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 32
                        case 42: {
                            colour_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 42
                        case 48: {
                            selected_ = input.readBool();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 48
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>uint64 epoch = 1;</code>
         *
         * @return The epoch.
         */
        @java.lang.Override
        public long getEpoch() {
            return epoch_;
        }

        /**
         * <code>uint64 epoch = 1;</code>
         *
         * @param value The epoch to set.
         * @return This builder for chaining.
         */
        public Builder setEpoch(long value) {

            epoch_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 epoch = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEpoch() {
            bitField0_ = (bitField0_ & ~0x00000001);
            epoch_ = 0L;
            onChanged();
            return this;
        }

        private void ensureSideIsMutable() {
            if ((bitField0_ & 0x00000002) == 0) {
                side_ = new java.util.ArrayList<com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer>(side_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer> getSideList() {
            if (sideBuilder_ == null) {
                return java.util.Collections.unmodifiableList(side_);
            } else {
                return sideBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public int getSideCount() {
            if (sideBuilder_ == null) {
                return side_.size();
            } else {
                return sideBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer getSide(int index) {
            if (sideBuilder_ == null) {
                return side_.get(index);
            } else {
                return sideBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder setSide(
                int index, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer value) {
            if (sideBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSideIsMutable();
                side_.set(index, value);
                onChanged();
            } else {
                sideBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder setSide(
                int index, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder builderForValue) {
            if (sideBuilder_ == null) {
                ensureSideIsMutable();
                side_.set(index, builderForValue.build());
                onChanged();
            } else {
                sideBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder addSide(com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer value) {
            if (sideBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSideIsMutable();
                side_.add(value);
                onChanged();
            } else {
                sideBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder addSide(
                int index, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer value) {
            if (sideBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSideIsMutable();
                side_.add(index, value);
                onChanged();
            } else {
                sideBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder addSide(
                com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder builderForValue) {
            if (sideBuilder_ == null) {
                ensureSideIsMutable();
                side_.add(builderForValue.build());
                onChanged();
            } else {
                sideBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder addSide(
                int index, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder builderForValue) {
            if (sideBuilder_ == null) {
                ensureSideIsMutable();
                side_.add(index, builderForValue.build());
                onChanged();
            } else {
                sideBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder addAllSide(
                java.lang.Iterable<? extends com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer> values) {
            if (sideBuilder_ == null) {
                ensureSideIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, side_);
                onChanged();
            } else {
                sideBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder clearSide() {
            if (sideBuilder_ == null) {
                side_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                sideBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public Builder removeSide(int index) {
            if (sideBuilder_ == null) {
                ensureSideIsMutable();
                side_.remove(index);
                onChanged();
            } else {
                sideBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder getSideBuilder(
                int index) {
            return getSideFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder getSideOrBuilder(
                int index) {
            if (sideBuilder_ == null) {
                return side_.get(index);
            } else {
                return sideBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public java.util.List<? extends com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder>
        getSideOrBuilderList() {
            if (sideBuilder_ != null) {
                return sideBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(side_);
            }
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder addSideBuilder() {
            return getSideFieldBuilder().addBuilder(
                    com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.getDefaultInstance());
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder addSideBuilder(
                int index) {
            return getSideFieldBuilder().addBuilder(
                    index, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.getDefaultInstance());
        }

        /**
         * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer side = 2;</code>
         */
        public java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder>
        getSideBuilderList() {
            return getSideFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder>
        getSideFieldBuilder() {
            if (sideBuilder_ == null) {
                sideBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer.Builder, com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBufferOrBuilder>(
                        side_,
                        ((bitField0_ & 0x00000002) != 0),
                        getParentForChildren(),
                        isClean());
                side_ = null;
            }
            return sideBuilder_;
        }

        /**
         * <code>string title = 3;</code>
         *
         * @return The title.
         */
        public java.lang.String getTitle() {
            java.lang.Object ref = title_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                title_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string title = 3;</code>
         *
         * @param value The title to set.
         * @return This builder for chaining.
         */
        public Builder setTitle(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            title_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>string title = 3;</code>
         *
         * @return The bytes for title.
         */
        public com.google.protobuf.ByteString
        getTitleBytes() {
            java.lang.Object ref = title_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                title_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string title = 3;</code>
         *
         * @param value The bytes for title to set.
         * @return This builder for chaining.
         */
        public Builder setTitleBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            title_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>string title = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTitle() {
            title_ = getDefaultInstance().getTitle();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>int32 titleStringsId = 4;</code>
         *
         * @return The titleStringsId.
         */
        @java.lang.Override
        public int getTitleStringsId() {
            return titleStringsId_;
        }

        /**
         * <code>int32 titleStringsId = 4;</code>
         *
         * @param value The titleStringsId to set.
         * @return This builder for chaining.
         */
        public Builder setTitleStringsId(int value) {

            titleStringsId_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>int32 titleStringsId = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTitleStringsId() {
            bitField0_ = (bitField0_ & ~0x00000008);
            titleStringsId_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>string colour = 5;</code>
         *
         * @return The colour.
         */
        public java.lang.String getColour() {
            java.lang.Object ref = colour_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                colour_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string colour = 5;</code>
         *
         * @param value The colour to set.
         * @return This builder for chaining.
         */
        public Builder setColour(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            colour_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>string colour = 5;</code>
         *
         * @return The bytes for colour.
         */
        public com.google.protobuf.ByteString
        getColourBytes() {
            java.lang.Object ref = colour_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                colour_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string colour = 5;</code>
         *
         * @param value The bytes for colour to set.
         * @return This builder for chaining.
         */
        public Builder setColourBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            colour_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>string colour = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearColour() {
            colour_ = getDefaultInstance().getColour();
            bitField0_ = (bitField0_ & ~0x00000010);
            onChanged();
            return this;
        }

        /**
         * <code>bool selected = 6;</code>
         *
         * @return The selected.
         */
        @java.lang.Override
        public boolean getSelected() {
            return selected_;
        }

        /**
         * <code>bool selected = 6;</code>
         *
         * @param value The selected to set.
         * @return This builder for chaining.
         */
        public Builder setSelected(boolean value) {

            selected_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>bool selected = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSelected() {
            bitField0_ = (bitField0_ & ~0x00000020);
            selected_ = false;
            onChanged();
            return this;
        }

        @java.lang.Override
        public Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer)
    }

}

