// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roll_history.proto

// Protobuf Java Version: 3.25.1
package com.github.jameshnsears.chance.data.protocolbuffer;

public interface RollListProtocolBufferOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.protocolbuffer.RollListProtocolBuffer)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer roll = 1;</code>
     */
    java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer>
    getRollList();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer roll = 1;</code>
     */
    com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer getRoll(int index);

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer roll = 1;</code>
     */
    int getRollCount();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer roll = 1;</code>
     */
    java.util.List<? extends com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBufferOrBuilder>
    getRollOrBuilderList();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBuffer roll = 1;</code>
     */
    com.github.jameshnsears.chance.data.protocolbuffer.RollProtocolBufferOrBuilder getRollOrBuilder(
            int index);
}
