// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 3.25.1
package com.github.jameshnsears.chance.data.protocolbuffer;

public interface SettingsProtocolBufferOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.protocolbuffer.SettingsProtocolBuffer)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 tabRowChance = 1;</code>
     *
     * @return The tabRowChance.
     */
    int getTabRowChance();

    /**
     * <code>int32 bagZoom = 2;</code>
     *
     * @return The bagZoom.
     */
    int getBagZoom();

    /**
     * <code>bool bagDemoBag = 3;</code>
     *
     * @return The bagDemoBag.
     */
    boolean getBagDemoBag();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer rollSelectedDice = 4;</code>
     */
    java.util.List<com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer>
    getRollSelectedDiceList();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer rollSelectedDice = 4;</code>
     */
    com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer getRollSelectedDice(int index);

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer rollSelectedDice = 4;</code>
     */
    int getRollSelectedDiceCount();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer rollSelectedDice = 4;</code>
     */
    java.util.List<? extends com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBufferOrBuilder>
    getRollSelectedDiceOrBuilderList();

    /**
     * <code>repeated .com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBuffer rollSelectedDice = 4;</code>
     */
    com.github.jameshnsears.chance.data.protocolbuffer.DiceProtocolBufferOrBuilder getRollSelectedDiceOrBuilder(
            int index);

    /**
     * <code>bool rollSequentially = 5;</code>
     *
     * @return The rollSequentially.
     */
    boolean getRollSequentially();

    /**
     * <code>int32 rollZoom = 6;</code>
     *
     * @return The rollZoom.
     */
    int getRollZoom();

    /**
     * <code>bool rollHistory = 7;</code>
     *
     * @return The rollHistory.
     */
    boolean getRollHistory();

    /**
     * <code>bool rollTitle = 8;</code>
     *
     * @return The rollTitle.
     */
    boolean getRollTitle();

    /**
     * <code>bool rollSideNumber = 9;</code>
     *
     * @return The rollSideNumber.
     */
    boolean getRollSideNumber();

    /**
     * <code>bool rollTotal = 10;</code>
     *
     * @return The rollTotal.
     */
    boolean getRollTotal();

    /**
     * <code>bool rollSound = 11;</code>
     *
     * @return The rollSound.
     */
    boolean getRollSound();
}
