// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: side.proto

// Protobuf Java Version: 3.25.1
package com.github.jameshnsears.chance.data.protocolbuffer;

public interface SideProtocolBufferOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.github.jameshnsears.chance.data.protocolbuffer.SideProtocolBuffer)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 number = 1;</code>
     *
     * @return The number.
     */
    int getNumber();

    /**
     * <code>string colour = 2;</code>
     *
     * @return The colour.
     */
    java.lang.String getColour();

    /**
     * <code>string colour = 2;</code>
     *
     * @return The bytes for colour.
     */
    com.google.protobuf.ByteString
    getColourBytes();

    /**
     * <code>string imageBase64 = 3;</code>
     *
     * @return The imageBase64.
     */
    java.lang.String getImageBase64();

    /**
     * <code>string imageBase64 = 3;</code>
     *
     * @return The bytes for imageBase64.
     */
    com.google.protobuf.ByteString
    getImageBase64Bytes();

    /**
     * <code>int32 imageDrawableId = 4;</code>
     *
     * @return The imageDrawableId.
     */
    int getImageDrawableId();

    /**
     * <code>string description = 5;</code>
     *
     * @return The description.
     */
    java.lang.String getDescription();

    /**
     * <code>string description = 5;</code>
     *
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
    getDescriptionBytes();

    /**
     * <code>int32 descriptionStringsId = 6;</code>
     *
     * @return The descriptionStringsId.
     */
    int getDescriptionStringsId();

    /**
     * <code>string descriptionColour = 7;</code>
     *
     * @return The descriptionColour.
     */
    java.lang.String getDescriptionColour();

    /**
     * <code>string descriptionColour = 7;</code>
     *
     * @return The bytes for descriptionColour.
     */
    com.google.protobuf.ByteString
    getDescriptionColourBytes();
}
