name: Setup Gradle Environment
description: Setup Java, custom Gradle cache

inputs:
  java-version:
    description: 'Java version to use'
    default: '21'
  distribution:
    description: 'Java distribution'
    default: 'zulu'

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
        restore-keys: |
          gradle-
