name: codecov.app.androidTest

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  fdroid:
    name: fdroid
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 36
            run-tests: true

    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Restore cache gradle
        uses: ./.github/actions/cache-gradle

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "${LOCAL_PROPERTIES}" | base64 -d > local.properties

      - name: google-services.json
        env:
          GOOGLE_PLAY_JSON_DEVELOPMENT: ${{ secrets.GOOGLE_PLAY_JSON_DEVELOPMENT }}
        run: echo "${GOOGLE_PLAY_JSON_DEVELOPMENT}" | base64 -d > app/google-services.json

      - name: Restore cache avd
        uses: ./.github/actions/cache-avd
        with:
          api-level: ${{ matrix.api-level }}

      - name: jacocoFdroidAndroidTestReport
        if: matrix.run-tests == true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default   # without GMS
          arch: x86_64
          ram-size: 4096m
          heap-size: 512m
          avd-name: ${{ matrix.api-level }}
          disable-animations: true
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb logcat -c
            adb logcat > logcat.txt &
            ./gradlew :app:jacocoFdroidAndroidTestReport -Dorg.gradle.jvmargs="-Xmx2048m"

      - name: codecov
        if: matrix.run-tests == true
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          files: ./app/build/reports/jacoco/androidTest.xml
          flags: app-androidTest
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: artifact logcat
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: fdroid-logcat-${{ matrix.api-level }}
          path: logcat.txt

      - name: artifact reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: fdroid-${{ matrix.api-level }}
          path: |
            **/build/reports/*
