name: static.analysis

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dsonar.gradle.skipCompile=true -Dorg.gradle.configureondemand=true"

jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true

      - name: Restore cache gradle
        uses: ./.github/actions/cache-gradle

      - name: gradlew
        run: ./gradlew detekt -x test --parallel --max-workers 2 -Dorg.gradle.jvmargs="-Xmx2048m"

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true

      - name: Restore cache gradle
        uses: ./.github/actions/cache-gradle

      - name: gradlew
        run: ./gradlew ktlintCheck --parallel --max-workers 2 -Dorg.gradle.jvmargs="-Xmx2048m"

  lintFdroidDebug:
    name: lintFdroidDebug
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true

      - name: Restore cache gradle
        uses: ./.github/actions/cache-gradle

      - name: lint
        run: |
          set -x
          ./gradlew :app:lintFdroidDebug --parallel --max-workers 2 -Dorg.gradle.jvmargs="-Xmx2048m"
