name: test-codecov

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_VERSION: 1

jobs:
  test-codecov:
    name: test-codecov
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./ci_clear_gradle_cache.sh

      - name: gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.CACHE_VERSION }}-${{ hashFiles('**/**.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "${LOCAL_PROPERTIES}" | base64 -d > local.properties

      - name: google-services.json
        env:
          GOOGLE_PLAY_JSON_DEVELOPMENT: ${{ secrets.GOOGLE_PLAY_JSON_DEVELOPMENT }}
        run: echo "${GOOGLE_PLAY_JSON_DEVELOPMENT}" | base64 -d > app/google-services.json

      - name: gradlew
        run: |
          set -x
          ./gradlew jacocoTestReport
          ls -al ./module/data/build/reports/jacoco/test.xml
          ls -al ./module/ui/build/reports/jacoco/test.xml
          ls -al ./module/ui-dialog-bag/build/reports/jacoco/test.xml

      - name: codecov - data.test
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./module/data/build/reports/jacoco/test.xml
          flags: data.test
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: codecov - ui.test
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./module/ui/build/reports/jacoco/test.xml
          flags: ui.test
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: codecov - ui-dialog-bag.test
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./module/ui-dialog-bag/build/reports/jacoco/test.xml
          flags: ui-dialog-bag.test
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
